spring:
  application:
    name: decisionengine
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_AMQP_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: /

logging:
  file:
    name: ${user.home}/Downloads/grapehealth-decisionengine.log
  level:
    org.springframework.amqp: INFO
    com.rabbitmq.client: INFO

server:
  port: 8081