spring:
  application:
    name: decisionengine
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_AMQP_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: /
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE:verify-full}&sslrootcert=${PG_SSL_ROOT_CERT}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  file:
    name: ${SPRING_BOOT_LOGS_DIR:${user.home}/Downloads}/grapehealth-decisionengine.log
  level:
    org.springframework.amqp: INFO
    com.rabbitmq.client: INFO

server:
  port: 8081
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
    include-exception: false
    whitelabel:
      enabled: false